type CategoryMutation {
  update(categoryId: ID!, value: UpdateCategoryInput!): Category!
}

type AccountQuery {
  list: [Account!]!
}

type Mutation {
  accounts: AccountMutation!
  currencies: CurrencyMutation!
  categories: CategoryMutation!
}

type Category {
  id: ID!
  name: String!
  children: [Category!]!
}

type Currency {
  id: ID!
  name: String!
  code: String!
  symbol: String
  numericCode: Int!
  digits: Int!
  selected: Boolean!
  rate: CalculatedRate
}

type CurrencyMutation {
  setSelected(currencyId: ID!, value: Boolean!): Currency!
}

enum AccountType {
  VAULT
  CREDIT
  LOAN
  PROMISE
}

type Query {
  apiVersion: String!
  accounts: AccountQuery!
  currencies: CurrencyQuery!
  categories: CategoryQuery!
}

type AccountMutation {
  create(data: NewAccountInput!): Account!
}

type CategoryQuery {
  list: [Category!]!
}

input UpdateCategoryInput {
  name: String
  icon: String
  description: String
}

input NewAccountInput {
  name: String!
  currencyId: ID!
  accountType: AccountType!
  icon: String
}

type CalculatedRate {
  rate: Float!
}

type Account {
  id: ID!
  name: String!
  kind: AccountType!
  currency: Currency!
}

type CurrencyQuery {
  list: [Currency!]!
}

schema {
  query: Query
  mutation: Mutation
}

