//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "exchange_rate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_id: i32,
    pub to_id: i32,
    pub rate: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::ToId",
        to = "super::currency::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currency2,
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::FromId",
        to = "super::currency::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currency1,
}

impl ActiveModelBehavior for ActiveModel {}
