//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transfer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub debit_transaction_id: String,
    pub credit_transaction_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::CreditTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transaction2,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::DebitTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transaction1,
}

impl ActiveModelBehavior for ActiveModel {}
